@startuml
    allow_mixing
    actor ":Administrador" as admin
    boundary ":IntConsulNotif" as intConsulNotif
    control "ControladorNotif" as ctrlNotif
    collections ":PlantillaNotificacion" as plantiList
    

    admin -> intConsulNotif : "1.opcionConsultarNotificaciones()"
    intConsulNotif -> ctrlNotif : "2.consultarNotificaciones()"
    ctrlNotif -> ctrlNotif : "3.buscarNotificaciones()"
    ctrlNotif -up-> plantiList : "4.mostrarNotificaciones()"
    

@enduml
