
@startuml Casos-de-Uso

actor Usuario

participant "Operadora" as O
participant "Distribuidor" as D
participant "Encargado" as E
participant "Presidente" as P

Usuario -> O: Solicita Pedido
O -> O: Verifica si es cliente
O -> O: Registra cliente
O -> O: Informa precio
O -> O: Registra pedido
O -> O: Genera listado de pedidos
O -> O: Genera factura
O -> D: Entrega listado de pedidos
D -> D: Se dirige al domicilio
D -> D: Entrega pedido
D -> D: Realiza cobranza
D -> D: Entrega factura
D -> D: Hace firmar al cliente
D -> D: Rinde trabajo
D -> E: Entrega dinero y/o cheques
D -> E: Entrega listado de pedidos
D -> E: Entrega firma del cliente
E -> E: Registra fecha y hora de entrega
E -> E: Registra forma de pago
E -> E: Registra datos del cheque
E -> E: Registra observaciones
E -> E: Deja como pendiente pedidos no entregados
E -> E: Confecciona resumen de ingresos
O -> O: Registra cancelación de pedido
O -> D: Comunica cancelación de pedido
O -> O: Registra anulación de factura
P -> P: Informa nuevos precios
P -> P: Solicita información estadística

@enduml