@startuml Colaboraciones
    allow_mixing
    actor Cliente
    actor Operadora
    actor Distribuidor
    actor Encargado
    actor Contador
    actor Presidente
    Cliente --> Operadora : Solicita pedido
    Operadora -down-> Cliente : Solicita datos
    Cliente -down-> Operadora : Entrega datos
    Operadora -down-> Cliente : Informa precio
    Cliente -up-> Operadora : Acepta
    Operadora -down-> Encargado : Registra pedido
    Encargado -right-> Operadora : Registra pedido
    Operadora -down-> Cliente : Informa fecha de entrega
    Operadora -> Distribuidor : Genera listado
    Distribuidor -> Operadora : Recibe listado
    Distribuidor -> Cliente : Entrega pedido
    Cliente -> Distribuidor : Paga
    Distribuidor -> Cliente : Entrega factura
    Distribuidor -> Encargado : Rinde trabajo
    Encargado -> Distribuidor : Registra datos
    Encargado -> Contador : Genera resumen
    Contador -> Encargado : Recibe resumen
    Presidente -down-> Encargado : Informa nuevos precios
    Encargado -up-> Presidente: Registra nuevos precios

    Presidente -up-> Encargado : Solicita informacion
    Encargado -down-> Presidente : Entrega informacion
@enduml