
@startuml Casos-de-Uso

actor Usuario

participant "Operadora" as O
participant "Distribuidor" as D
participant "Encargado" as E
participant "Presidente" as P
participant "Contador" as C

Usuario -> O: 1.Solicita Pedido
O -> O: 2.Verifica si es cliente
O -> O: 3.Registra cliente
O -> O: 4.Registra Pedido
O -> O: 5.Informa detalle de Pedido
O -> O: 6.Registra pedido
O -> O: 7.Genera listado de pedidos
O -> O: 8.Genera factura
O -> D: 9.Entrega listado de pedidos
D -> D: 10.Se dirige al domicilio
D -> D: 11.Entrega pedido
D -> D: 12.Realiza cobranza
D -> D: 13.Entrega factura
D -> D: 14.Hace firmar al cliente
D -> D: 15.Rinde trabajo
D -> E: 16.Entrega dinero y/o cheques
D -> E: 17.Entrega listado de pedidos
D -> E: 18.Entrega firma del cliente
E -> E: 19.Registra fecha y hora de entrega
E -> E: 20.Registra forma de pago
E -> E: 21.Registra datos del cheque
E -> E: 22.Registra observaciones
E -> E: 23.Deja como pendiente pedidos no entregados
E -> E: 24.Confecciona resumen de ingresos
E -> C: 25.Genera resumen
C -> E: 26.Recibe resumen
O -> O: 27.Registra cancelación de pedido
O -> D: 28.Comunica cancelación de pedido
O -> O: 29.Registra anulación de factura
P -> P: 30.Informa nuevos precios
P -> P: 31.Solicita información estadística

@enduml