@startuml Colaboraciones
    allow_mixing
    actor Cliente
    actor Operadora
    actor Distribuidor
    actor Encargado
    actor Contador
    actor Presidente
    Cliente -> Operadora : Solicita pedido
    Operadora -> Cliente : Solicita datos
    Cliente -> Operadora : Entrega datos
    Operadora -> Cliente : Informa precio
    Cliente -> Operadora : Acepta
    Operadora -> Encargado : Registra pedido
    Encargado -> Operadora : Registra pedido
    Operadora -> Cliente : Informa fecha de entrega
    Operadora -> Distribuidor : Genera listado
    Distribuidor -> Operadora : Recibe listado
    Distribuidor -> Cliente : Entrega pedido
    Cliente -> Distribuidor : Paga
    Distribuidor -> Cliente : Entrega factura
    Distribuidor -> Encargado : Rinde trabajo
    Encargado -> Distribuidor : Registra datos
    Encargado -> Contador : Genera resumen
    Contador -> Encargado : Recibe resumen
    Presidente -> Encargado : Informa nuevos precios
    Encargado -> Presidente : Registra nuevos precios
    Presidente -> Encargado : Solicita informacion
    Encargado -> Presidente : Entrega informacion
@enduml