@startuml
class Proveedor {
    -razonSocial:String
    -CUIT:String
    -condicionIVA:String
    -domicilio:String
    -localidad:String
    -telefono:String
    -fax:String
}

class Articulo {
    -nombre:String
    -descripcion:String
    -unidadMedida:String
    -precioUnitario:Double
}

class Pedido {
    -fecha:Date
    -proveedor:Proveedor
    -articulos:Articulo[]
}
class Localidad {
    -nombre:String
    -codigoPostal:String
}

class Domicilio {
    -calle:String
    -numero:String
    -piso:String
    -departamento:String
    -localidad:Localidad
    +void Mostrar()
}

package Ejercicio1 {
}

Pedido "1" -- "*" Articulo
Pedido "1" -- "1" Proveedor
Domicilio -- "1" Localidad
Proveedor -up- Persona
Proveedor -- Domicilio

@enduml